n_english = int(input())
students_en = set(map(int,input().strip().split()))
n_french = int(input())
students_fr = set(map(int,input().strip().split()))
symmetric_difference = students_en.symmetric_difference(students_fr)
print(len(symmetric_difference))